puppet module install basti1302/windows_path
puppet module install liamjbennett/windows_firewall
puppet module install martezr/windows_domain_controller
puppet module install puppetlabs/vcenter
puppet module install softek/zabbixagent
puppet module install simondean/net_share
puppet module install adenning/winfacts
puppet module install liamjbennett/dotnet
puppet module install rismoney/windowsnetwork
